# # .pre-commit-config.yaml

# repos:
#   - repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v4.4.0
#     hooks:
#       - id: trailing-whitespace
#       - id: end-of-file-fixer
#       - id: check-yaml
#         exclude: ^mkdocs\.yml$
#       - id: check-merge-conflict
# #      - id: check-added-large-files

#   - repo: local
#     hooks:
#         - id: ruff
#           name: ruff
#           entry: ruff
#           language: python
#           types: [ python ]
#           args: [ '--fix']  # Automatically fix issues if possible
#           additional_dependencies: [ 'ruff==0.0.47' ]


#   - repo: https://github.com/PyCQA/pylint
#     rev: v2.17.5  # Use the latest version available
#     hooks:
#       - id: pylint
#         name: pylint-docstrings
#         entry: pylint
#         language: python
#         types: [python]
#         args:
#           - '--disable=all'  # Disable all checks
#           - '--enable=missing-function-docstring'  # Enable function docstring check
#           - '--disable=missing-module-docstring'  # Disable module docstring check
#           - '--disable=missing-class-docstring'  # Disable class docstring check
#           - '--output-format=colorized'
#         additional_dependencies: []

#   # Optionally, you can add black for code formatting
#   - repo: https://github.com/psf/black
#     rev: 23.7.0  # Use the latest version available
#     hooks:
#       - id: black
#         args: ['--line-length=120']

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.1.1
    hooks:
    -   id: black
        language_version: python3.11
        args: ["--line-length=79"]
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
